import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../core/theme.dart';
import '../../data/auth_store.dart';
import '../../data/store.dart';
import '../../documents/doc_models.dart';
import '../../documents/pdf_shared.dart';
import '../../documents/share_service.dart';
import '../signature_dialog.dart';
import '../widgets.dart';

class PaymentVouchersScreen extends StatefulWidget { const PaymentVouchersScreen({super.key}); @override State<PaymentVouchersScreen> createState()=>_PaymentVouchersScreenState(); }
class _PaymentVouchersScreenState extends State<PaymentVouchersScreen> {
  final List<Map<String,dynamic>> rows=[]; bool loading=false;
  @override void initState(){super.initState();_load();}
  Future<void> _load() async { setState(()=>loading=true); final r=await AppStore.instance.api?.get('/api/payment-vouchers'); if(mounted)setState((){loading=false;rows..clear()..addAll([for(final x in (r?.json is Map?(r!.json as Map)['rows'] as List? ?? []:[]))if(x is Map)x.cast<String,dynamic>()]);});}
  @override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.all(20),child:Column(children:[PageHeader(title:'Payment Vouchers',subtitle:'Official company expenditure and salary payments',icon:Icons.payments_outlined,actions:[FilledButton.icon(onPressed:_create,icon:const Icon(Icons.add),label:const Text('New voucher'))]),const SizedBox(height:14),Expanded(child:Card(child:loading?const Center(child:CircularProgressIndicator()):rows.isEmpty?const EmptyHint('No payment vouchers yet'):ListView.separated(itemCount:rows.length,separatorBuilder:(_,__)=>const Divider(height:1),itemBuilder:(_,i){final v=rows[i],paid=v['status']=='paid';return ListTile(leading:Icon(paid?Icons.verified:Icons.pending_actions,color:paid?Mtek.success:Mtek.warn),title:Text('PV-${_no(v)} — ${v['payee']}'),subtitle:Text('${v['particulars']} · ₦${v['amount']} · ${paid?'PAID':'PENDING CEO APPROVAL'}'),onTap:()=>_pdf(v),trailing:!paid&&AuthStore.instance.isCeo?FilledButton(onPressed:()=>_approve(v),child:const Text('Approve & Pay')):null);})))]));
  String _no(Map v)=>(v['serial'] as num? ?? 0).toInt().toString().padLeft(9,'0');
  Future<void> _create() async {final payee=TextEditingController(),part=TextEditingController(),amount=TextEditingController(),cheque=TextEditingController(),debit=TextEditingController();String method='transfer';final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(_,set)=>AlertDialog(title:const Text('New Payment Voucher'),content:SizedBox(width:520,child:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:payee,decoration:const InputDecoration(labelText:'Payee *')),TextField(controller:part,maxLines:3,decoration:const InputDecoration(labelText:'Particulars *')),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount (₦) *')),DropdownButtonFormField(value:method,items:['cash','transfer','cheque','pos'].map((x)=>DropdownMenuItem(value:x,child:Text(x.toUpperCase()))).toList(),onChanged:(x)=>set(()=>method=x??'cash'),decoration:const InputDecoration(labelText:'Payment method')),if(method=='cheque')TextField(controller:cheque,decoration:const InputDecoration(labelText:'Cheque No.')),TextField(controller:debit,decoration:const InputDecoration(labelText:'Debit A/C'))]))),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Sign & submit'))])));if(ok!=true)return;final signer=await confirmSignature(context);if(signer==null)return;final r=await AppStore.instance.api?.post('/api/payment-vouchers',{'date':DateTime.now().toIso8601String(),'payee':payee.text,'particulars':part.text,'amount':int.tryParse(amount.text.replaceAll(',',''))??0,'method':method,'cheque_no':cheque.text,'debit_account':debit.text,'passcode':AuthStore.instance.lastVerifiedPasscode??''});if(r==null||!r.ok){_snack('${r?.json is Map?(r!.json as Map)['error']:'Cloud unavailable'}');return;}await _load();_snack('Voucher submitted for CEO approval.');}
  Future<void> _approve(Map<String,dynamic> v)async{final s=await confirmSignature(context,force:true);if(s==null)return;final r=await AppStore.instance.api?.post('/api/payment-vouchers/approve',{'id':'${v['_id']}','passcode':AuthStore.instance.lastVerifiedPasscode??''});if(r==null||!r.ok){_snack('${r?.json is Map?(r!.json as Map)['error']:'Approval failed'}');return;}await AppStore.instance.refreshRemote();await _load();_snack('Voucher approved and posted as company expenditure.');}
  Future<void> _pdf(Map<String,dynamic> v)async{await MtekPdfFonts.load();final d=await rootBundle.load('assets/branding/logo.png'),logo=pw.MemoryImage(d.buffer.asUint8List());final pdf=pw.Document();pdf.addPage(pw.Page(pageFormat:PdfPageFormat.a4,margin:const pw.EdgeInsets.all(28),theme:pw.ThemeData.withFont(base:MtekPdfFonts.base,bold:MtekPdfFonts.bold),build:(_)=>pw.Column(children:[corporateHeader(logo),pw.SizedBox(height:16),pw.Text('PAYMENT VOUCHER',style:pw.TextStyle(fontSize:18,fontWeight:pw.FontWeight.bold,color:PdfColors.red900)),pw.SizedBox(height:12),pw.Row(mainAxisAlignment:pw.MainAxisAlignment.spaceBetween,children:[pw.Text('Date: ${v['voucher_date']}'),pw.Text('P. V. No: ${_no(v)}')]),ruledField('Payee:',value:'${v['payee']}'),ruledField('The sum of:',value:nairaInWords((v['amount'] as num).toDouble())),ruledField('Particulars:',value:'${v['particulars']}',maxLines:3),ruledField('Cheque No:',value:'${v['cheque_no']??''}'),ruledField('Debit A/C:',value:'${v['debit_account']??''}'),pw.SizedBox(height:18),pw.Text('Amount: ₦${v['amount']}',style:pw.TextStyle(fontSize:16,fontWeight:pw.FontWeight.bold)),pw.Spacer(),pw.Row(mainAxisAlignment:pw.MainAxisAlignment.spaceBetween,children:[pw.Text('Prepared/Checked by: ${v['prepared_name']??''}'),pw.Text('Approved/Paid by: ${v['approved_name']??'Pending'}')])])));final Uint8List b=await pdf.save();final filename='MFSL-PV-${_no(v)}.pdf';await archivePdfToCloud(bytes:b,filename:filename,description:'Payment Voucher ${_no(v)} · ${v['payee']}');if(!mounted)return;final action=await showDialog<String>(context:context,builder:(c)=>AlertDialog(title:const Text('Payment Voucher PDF'),content:const Text('This document is saved to the cloud. Choose what to do next.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,'print'),child:const Text('Print')),TextButton(onPressed:()=>Navigator.pop(c,'download'),child:const Text('Download')),FilledButton(onPressed:()=>Navigator.pop(c,'share'),child:const Text('Share'))]));if(action=='print')await Printing.layoutPdf(onLayout:(_)async=>b);if(action=='download'){final o=await savePdf(bytes:b,filename:filename);_snack(o.message);}if(action=='share'){final o=await dispatchPdf(bytes:b,filename:filename);_snack(o.message);}}
  void _snack(String x){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(x)));}
}
